// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {IERC1155} from "@openzeppelin/contracts/token/ERC1155/IERC1155.sol";
import {ERC1155Holder} from "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Holder.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

import {WarptoadERC20} from "./WarptoadERC20.sol";
import {WarptoadERC1155} from "./WarptoadERC1155.sol";
import {TokenMetadata} from "./libraries/TokenMetadata.sol";

import {
    SkinnyIMTPoseidon2WriteStorage,
    SkinnyIMTDataStorage
} from "@warptoad/skinny-imt.sol/poseidon2/SkinnyIMTPoseidon2WriteStorage.sol";
//import {SkinnyIMTDataEvent} from "@warptoad/skinny-imt.sol/poseidon2/SkinnyIMTPoseidon2WriteEvent.sol";
import {SkinnyIMTPoseidon2Read} from "@warptoad/skinny-imt.sol/poseidon2/SkinnyIMTPoseidon2Read.sol";
import {SkinnyIMTReadableStorage} from "@warptoad/skinny-imt.sol/SkinnyIMTReadableStorage.sol";

import {Poseidon2} from "poseidon2-evm/src/bn254/Poseidon2.sol";

enum AssetType {
    ERC20,
    ERC721,
    ERC1155
}

/// @dev generated by `pnpm noir`, see WarptoadVerifier.sol
interface IWarptoadVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}

// ------ mirrors of the pub structs in circuits/src/main.nr ------
// field order here == public input order in the proof, see formatPublicInputs

/// @dev `giga_first_valid_index`, `giga_last_valid_index` and `current_giga_index` are not here,
/// the contract fills those in from its own storage
struct PubRootsAndIndexes {
    uint256 localRoot; // spend commitments proven against this skip the giga proof
    uint256 localEdgeIndex; // treeSize - 1 at the time `localRoot` was the root
    uint256 gigaRoot; // TODO not checked against anything yet, giga tree is not plugged in
    uint256 gigaEdgeIndex;
}

struct TimeStamps {
    uint256 proofExpireTimeStamp; // proof is valid while block.timestamp <= this
    uint256 historicTimeStamp; // proof claims block.timestamp >= this
}

/// @dev one per recipient commitment slot, `assetId == 0` means that slot is a normal shielded commitment.
/// Unshielding slots must come first: [unshield, unshield, normal, normal] is fine, [normal, unshield, ..] is not
struct UnshieldingCommitment {
    // the recipient is stored where usually owner hash is stored
    uint256 recipient;
    uint256 amount;
    uint256 assetId;
}

/// @dev tells the contract which wrapper an unshielding slot's `assetId` is, it can't invert the hash itself
struct UnshieldTarget {
    address wrapper;
    uint256 id; // 0 for ERC20
}

/// @dev everything `verifyShieldedTx` needs. All arrays are CIRCUIT_SIZE long
struct ShieldedTx {
    PubRootsAndIndexes roots;
    TimeStamps timeStamps; // checked against block.timestamp
    // one per recipient slot, unshielding ones first. `assetId != 0` means: not inserted in the tree, but `amount`
    // of `unshieldTargets[i]` is minted to `ownerHash` (an eth address when unshielding)
    UnshieldingCommitment[] unshieldingCommitments;
    UnshieldTarget[] unshieldTargets; // ignored (zeroes) where `unshieldingCommitments[i].assetId == 0`
    uint256[] nullifiers; // fakes included, all get stored
    uint256[] recipientCommitmentsHashes; // fakes included, inserted in the tree except unshielding slots
    // one encrypted note per recipient slot, fakes and unshields included so every slot looks the same. See src/messages.ts
    // bound to the proof through `public_hash`, so a relayer can't swap them
    bytes[] messages;
    bytes proof; // of circuits/src/main.nr, `public_hash` is `hashPublic(messages)`
}

/**
 * @title Warptoad
 * @author Jim Jim Valkema, nodestarQ
 * @notice does NOT support rebasing tokens!
 */
contract Warptoad is ERC1155Holder, ReentrancyGuard, SkinnyIMTReadableStorage {
    using SafeERC20 for IERC20;

    SkinnyIMTDataStorage commitmentTree;

    string symbolPreFix;
    string namePreFix;
    string public chainSymbol;
    string public chainName;
    uint64 public immutable gigaIndex;

    /// @notice verifies proofs of the main circuit, see circuits/src/main.nr
    IWarptoadVerifier public immutable verifier;
    /// @notice mirrors `CIRCUIT_SIZE` in circuits/src/constants.nr: amount of spend and recipient commitment slots per proof
    uint256 public immutable CIRCUIT_SIZE;
    /// @dev roots, indexes, timestamps and public hash. Everything that isn't an array of CIRCUIT_SIZE
    uint256 private constant PUBLIC_INPUTS_HEAD = 10;
    /// @notice inclusive range of giga tree leaves a proof may spend from. TODO setter
    uint256 public gigaFirstValidIndex;
    uint256 public gigaLastValidIndex;

    /// @notice Wrapper token deployed for an underlying ERC-20, or zero if never wrapped.
    mapping(address underlying => address wrapper) public erc20WrapperOf;

    /// @notice Wrapper collection deployed for an underlying ERC-1155, or zero if never wrapped.
    mapping(address underlying => address wrapper) public erc1155WrapperOf;

    struct Underlying {
        address token;
        // not actually chainId, chainId changes when forking, causing user only able to unshield on the chain that did not fork
        uint64 chainWarpDomain;
    }

    /// @notice Underlying a wrapper redeems for. Non-zero exactly for tokens this vault deployed.
    mapping(address wrapper => Underlying underlying) public underlyingOf;

    /// @notice underlying tokens where wrapping is blocked (unwrapping is always allowed), only constructor and closeUndercollateralizedPool can add
    mapping(address underlying => bool closed) public closedPools;
    /// @notice every root the commitment tree ever had, and its size at that time. 0 means unknown root
    mapping(uint256 localRoot => uint256 treeSize) public localRoots;
    // can also contain syncRoot
    mapping(uint256 gigaRoot => uint256 treeSize) public gigaRoots;

    // TODO maybe do just bool
    /// @notice spent commitments. Stores the block number they got spent in, 0 means unspent
    mapping(uint256 nullifier => uint256 blockNumber) public nullifiers;

    event ERC20WrapperCreated(address indexed underlying, address indexed wrapper);
    event ERC1155WrapperCreated(address indexed underlying, address indexed wrapper);
    event ERC20Wrapped(address indexed underlying, address indexed wrapper, address indexed to, uint256 amount);
    event ERC20Unwrapped(address indexed underlying, address indexed wrapper, address indexed to, uint256 amount);
    event ERC1155Wrapped(
        address indexed underlying, address indexed wrapper, address indexed to, uint256 id, uint256 amount
    );
    event ERC1155Unwrapped(
        address indexed underlying, address indexed wrapper, address indexed to, uint256 id, uint256 amount
    );

    /// @notice asset is no longer allowed to be wrapped (unwrapping allowed)
    event PoolClosed(address indexed underlying);

    // TODO technically we don't need commitment?
    // practically i would be nice to look up: "did this commitment shield/unshield", so maybe keep it and make it indexed
    event Shielded(address indexed wrapper, uint256 assetId, uint256 amount, uint256 commitment);
    /// @notice indexed so wallets can check if a commitment was spent
    event Nullified(uint256 indexed nullifier);
    // same TODO as Shielded
    event Unshielded(address indexed wrapper, address indexed recipient, uint256 assetId, uint256 amount);
    /// @notice encrypted note for whoever owns `commitment`, only they can tell it is theirs. See src/messages.ts
    /// one per inserted commitment, fakes too. Not indexed on purpose: wallets scan all of them
    event Message(uint256 commitment, bytes message);

    /// @dev Thrown when unwrapping a token this vault did not issue, or issued for the other standard.
    error NotAWrapper(address token);
    /// @dev Thrown when wrapping an underlying whose pool is closed. Unwrapping it still works.
    error PoolIsClosed(address token);
    error ZeroAmount();
    error ZeroAddress();
    error WrongTreeId();
    error WrongCircuitSize(uint256 expected, uint256 got);
    error UnknownLocalRoot(uint256 root);
    error WrongLocalEdgeIndex(uint256 expected, uint256 got);
    error UnshieldingSlotsNotFirst(uint256 slot);
    error ProofExpired(uint256 expiredAt, uint256 now);
    error HistoricTimeStampInFuture(uint256 historic, uint256 now);
    error NullifierAlreadySpent(uint256 nullifier);
    error WrongAssetId(address wrapper, uint256 expected, uint256 got);
    error RecipientNotAnAddress(uint256 recipient);
    error VerificationFailed();

    /**
     *
     * @param _symbolPreFix: shortened name of the chain this contract is deployed on, used for wrapper symbol
     * @param _namePreFix: shortened name of the chain this contract is deployed on, used for wrapper symbol
     * @param _chainSymbol: shortened name of the chain this contract is deployed on, used for wrapper symbol
     * @param _chainName: shortened name of the chain this contract is deployed on, used for wrapper symbol
     * @param _gigaIndex:
     * @param _verifier: WarptoadVerifier.sol, generated from the circuit with `pnpm noir`
     * @param _circuitSize: CIRCUIT_SIZE of the circuit `_verifier` was generated for
     * @param _gigaFirstValidIndex: see gigaFirstValidIndex
     * @param _gigaLastValidIndex: see gigaLastValidIndex
     * @param _blockedTokens blocks these tokes from every being wrapped. Meant for rebasing tokens who can break solvency.
     * @notice don't worry: can only be done at constructor or if a rebase token is detected (with closeUndercollateralizedPool)
     * and you can always unwrap :D
     */
    constructor(
        string memory _symbolPreFix,
        string memory _namePreFix,
        string memory _chainSymbol,
        string memory _chainName,
        uint64 _gigaIndex,
        address _verifier,
        uint256 _circuitSize,
        uint256 _gigaFirstValidIndex,
        uint256 _gigaLastValidIndex,
        address[] memory _blockedTokens
    ) {
        symbolPreFix = _symbolPreFix;
        namePreFix = _namePreFix;
        chainSymbol = _chainSymbol;
        chainName = _chainName;
        gigaIndex = _gigaIndex;
        verifier = IWarptoadVerifier(_verifier);
        CIRCUIT_SIZE = _circuitSize;
        gigaFirstValidIndex = _gigaFirstValidIndex;
        gigaLastValidIndex = _gigaLastValidIndex;

        for (uint256 i = 0; i < _blockedTokens.length; i++) {
            closedPools[_blockedTokens[i]] = true;
            emit PoolClosed(_blockedTokens[i]);
        }

        SkinnyIMTPoseidon2WriteStorage.init(commitmentTree);
    }

    // ------ SkinnyIMT overrides -----------
    function supportsInterface(bytes4 interfaceId)
        public
        view
        virtual
        override(SkinnyIMTReadableStorage, ERC1155Holder)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    function commitmentTreeId() public view returns (uint256) {
        return commitmentTree.treeData.treeId;
    }

    function _getSkinnyStorageTree(uint256 treeId) internal view override returns (SkinnyIMTDataStorage storage) {
        if (treeId != commitmentTree.treeData.treeId) {
            revert WrongTreeId();
        }
        return commitmentTree;
    }
    //--------------------------------------

    /// @notice keccak with the last byte dropped, so it fits in a 254 bit field. Mirrored in src/hashing.ts
    /// @dev internal, not public: the contract is at the EIP-170 limit and every selector counts
    function keccak31Byte(bytes memory _data) internal pure returns (uint256) {
        return uint256(keccak256(_data)) >> 8;
    }

    /**
     * @notice public to save debugging headaches for sdk
     * @param contractAddr:
     * @param id:
     * @param originGigaIndex:
     * @param assetType:
     */
    function hashAssetId(
        address contractAddr,
        uint256 id, // 0 for ERC20
        uint256 originGigaIndex,
        AssetType assetType
    ) public pure returns (uint256) {
        return keccak31Byte(abi.encode(contractAddr, id, originGigaIndex, assetType));
    }

    //--------- shielding -----------
    /**
     * TODO: circuit contracts can be called here and just anything can be put into their storage
     * // since no zk is checking that here. Can't constrain it to only be join_split here for example
     * // since then we reveal owner_hash.
     * // single chain and cross chain swap should not have a issue with this tho
     * // person who locks is the one in control, and person who settles only read storage
     * // pre-nullification might be fucked. But assetId is created here so we can just say in that "i am not pre-nullified"
     * // i mean pre-nullification wont even use keccak for assetId, so it's good
     * // just to be sure pre-nullification should use poseidon2(originalAssetId,0,originGigaIndex,"PRE_NULL_ERC20")
     * // no commitment can be created here where "PRE_NULL_ERC20" is in assetId!
     * @param _wrapper: which wrapped token to shield
     * @param _amount: how much to shield
     * @param _preCommitmentHash: who will receive the shielded tokens, as a blinded hash
     * @param _message: encrypted note for the recipient, see src/messages.ts
     */
    function shieldErc20(address _wrapper, uint256 _amount, uint256 _preCommitmentHash, bytes calldata _message)
        public
    {
        address token = underlyingOf[_wrapper].token;
        if (token == address(0) || erc20WrapperOf[token] != _wrapper) revert NotAWrapper(_wrapper);
        // burn it, it is now shielded and can be unshielded on this or another chain, where a new wrapper token is minted :D
        WarptoadERC20(_wrapper).burn(msg.sender, _amount);
        uint256 _assetId = hashAssetId(token, 0, gigaIndex, AssetType.ERC20);
        // @notice, zemse poseidon implementation can only handle up to 3 inputs, transferDataHash is just to get around that
        uint256 _commitment = Poseidon2.hash_3(_preCommitmentHash, _assetId, _amount);
        (uint256 newRoot, uint256 index) = SkinnyIMTPoseidon2WriteStorage.insert(commitmentTree, _commitment);
        localRoots[newRoot] = index + 1;
        emit Shielded(_wrapper, _assetId, _amount, _commitment);
        emit Message(_commitment, _message);
    }

    /**
     * @param _wrapper: which wrapped collection to shield from
     * @param _id: which token id
     * @param _amount: how much of that id to shield
     * @param _preCommitmentHash: who will receive the shielded tokens, as a blinded hash
     * @param _message: encrypted note for the recipient, see src/messages.ts
     */
    function shieldErc1155(
        address _wrapper,
        uint256 _id,
        uint256 _amount,
        uint256 _preCommitmentHash,
        bytes calldata _message
    ) public {
        address collection = underlyingOf[_wrapper].token;
        if (collection == address(0) || erc1155WrapperOf[collection] != _wrapper) revert NotAWrapper(_wrapper);
        WarptoadERC1155(_wrapper).burn(msg.sender, _id, _amount);
        uint256 _assetId = hashAssetId(collection, _id, gigaIndex, AssetType.ERC1155);
        uint256 _commitment = Poseidon2.hash_3(_preCommitmentHash, _assetId, _amount);
        (uint256 newRoot, uint256 index) = SkinnyIMTPoseidon2WriteStorage.insert(commitmentTree, _commitment);
        localRoots[newRoot] = index + 1;
        emit Shielded(_wrapper, _assetId, _amount, _commitment);
        emit Message(_commitment, _message);
    }

    /**
     * @notice spends shielded commitments into new shielded commitments and/or unshields them into wrapper tokens.
     * A normal shielded transfer is just this with all `unshieldingCommitments[i].assetId == 0`.
     * @param _tx: see `ShieldedTx`
     */
    function verifyShieldedTx(ShieldedTx calldata _tx) external nonReentrant {
        _spendNullifiers(_tx.nullifiers);
        _checkRootsAndTimeStamps(_tx.roots, _tx.timeStamps);
        if (_tx.messages.length != CIRCUIT_SIZE) revert WrongCircuitSize(CIRCUIT_SIZE, _tx.messages.length);

        bytes32[] memory publicInputs = formatPublicInputs(
            _tx.roots,
            _tx.timeStamps,
            // the spender signed this inside the proof, so the relayer can't touch the messages
            hashPublic(_tx.messages),
            _tx.unshieldingCommitments,
            _tx.nullifiers,
            _tx.recipientCommitmentsHashes
        );
        if (!verifier.verify(_tx.proof, publicInputs)) revert VerificationFailed();
        // best save for last since it does expensive merkle tree inserts
        _insertOrUnshieldCommitments(_tx.unshieldingCommitments, _tx.unshieldTargets, _tx.recipientCommitmentsHashes);
        for (uint256 i = 0; i < CIRCUIT_SIZE; i++) {
            emit Message(_tx.recipientCommitmentsHashes[i], _tx.messages[i]);
        }
    }

    /**
     * @notice `public_hash` of the circuit, see `hash_public` in circuits/src/hashing.nr and `publicHashOf` in
     * src/messages.ts. Everything a shielded tx does in public goes in here so it is covered by the spender's
     * signature: Poseidon2(keccak(messages), keccak(other public things)). The second one is 0 until there are other things
     */
    function hashPublic(bytes[] calldata _messages) public view returns (uint256) {
        return Poseidon2.hash_2(keccak31Byte(abi.encode(_messages)), 0);
    }

    function _checkRootsAndTimeStamps(PubRootsAndIndexes calldata _roots, TimeStamps calldata _timeStamps)
        private
        view
    {
        uint256 treeSize = localRoots[_roots.localRoot];
        if (treeSize == 0) revert UnknownLocalRoot(_roots.localRoot);
        if (_roots.localEdgeIndex != treeSize - 1) revert WrongLocalEdgeIndex(treeSize - 1, _roots.localEdgeIndex);
        require(_roots.gigaRoot == uint256(0), "TODO plugin gigaRoot and check against history to enable cross-chain");
        if (_timeStamps.proofExpireTimeStamp < block.timestamp) {
            revert ProofExpired(_timeStamps.proofExpireTimeStamp, block.timestamp);
        }
        if (_timeStamps.historicTimeStamp > block.timestamp) {
            revert HistoricTimeStampInFuture(_timeStamps.historicTimeStamp, block.timestamp);
        }
    }

    /// @dev fakes included, they are indistinguishable from real ones and never collide with them
    function _spendNullifiers(uint256[] calldata _nullifiers) private {
        for (uint256 i = 0; i < _nullifiers.length; i++) {
            uint256 nullifier = _nullifiers[i];
            if (nullifiers[nullifier] != 0) revert NullifierAlreadySpent(nullifier);
            nullifiers[nullifier] = block.number;
            emit Nullified(nullifier);
        }
    }

    /**
     * @dev unshielding slots are minted and skipped, everything else (fakes included) goes in the tree.
     * Unshielding slots have to come first so the rest is one calldata slice for `insertMany`
     */
    function _insertOrUnshieldCommitments(
        UnshieldingCommitment[] calldata _unshieldingCommitments,
        UnshieldTarget[] calldata _unshieldTargets,
        uint256[] calldata _recipientCommitmentsHashes
    ) private {
        uint256 size = _recipientCommitmentsHashes.length;
        if (_unshieldTargets.length != size) revert WrongCircuitSize(size, _unshieldTargets.length);

        uint256 firstShielded = 0;
        for (uint256 i = 0; i < size; i++) {
            // skip commitments that are not unshielding
            if (_unshieldingCommitments[i].assetId == 0) continue;
            if (i != firstShielded) revert UnshieldingSlotsNotFirst(i);
            firstShielded = i + 1;
            _unshield(_unshieldingCommitments[i], _unshieldTargets[i]);
        }
        if (size > firstShielded) _insertCommitments(_recipientCommitmentsHashes[firstShielded:size]);
    }

    function _insertCommitments(uint256[] calldata _commitments) private {
        (uint256 newRoot,, uint256 nextIndex) = SkinnyIMTPoseidon2WriteStorage.insertMany(commitmentTree, _commitments);
        localRoots[newRoot] = nextIndex;
    }

    /**
     * @dev the circuit proved `_commitment` matches a recipient commitment owned by `_commitment.ownerHash`,
     * which is only an eth address because this is an unshield. Here we only need to find out which wrapper
     * `assetId` is and mint it
     */
    function _unshield(UnshieldingCommitment calldata _commitment, UnshieldTarget calldata _target) private {
        if (_commitment.recipient >> 160 != 0) revert RecipientNotAnAddress(_commitment.recipient);
        address recipient = address(uint160(_commitment.recipient));
        address wrapper = _target.wrapper;

        Underlying memory underlying = underlyingOf[wrapper];
        if (underlying.token == address(0)) revert NotAWrapper(wrapper);
        uint256 expectedAssetId;
        if (erc20WrapperOf[underlying.token] == wrapper) {
            expectedAssetId = hashAssetId(underlying.token, 0, underlying.chainWarpDomain, AssetType.ERC20);
            if (expectedAssetId != _commitment.assetId) {
                revert WrongAssetId(wrapper, expectedAssetId, _commitment.assetId);
            }
            WarptoadERC20(wrapper).mint(recipient, _commitment.amount);
        } else if (erc1155WrapperOf[underlying.token] == wrapper) {
            expectedAssetId = hashAssetId(underlying.token, _target.id, underlying.chainWarpDomain, AssetType.ERC1155);
            if (expectedAssetId != _commitment.assetId) {
                revert WrongAssetId(wrapper, expectedAssetId, _commitment.assetId);
            }
            WarptoadERC1155(wrapper).mint(recipient, _target.id, _commitment.amount);
        } else {
            revert NotAWrapper(wrapper);
        }
        emit Unshielded(wrapper, recipient, _commitment.assetId, _commitment.amount);
    }

    /**
     * @notice lays out the public inputs in the order the circuit expects them, see `PubInputs` in circuits/src/main.nr
     * public so the sdk can debug against it
     * @param _publicHash: what the circuit gets as `public_hash`, see hashPublic
     */
    function formatPublicInputs(
        PubRootsAndIndexes calldata _roots,
        TimeStamps calldata _timeStamps,
        uint256 _publicHash,
        UnshieldingCommitment[] calldata _unshieldingCommitments,
        uint256[] calldata _nullifiers,
        uint256[] calldata _recipientCommitmentsHashes
    ) public view returns (bytes32[] memory publicInputs) {
        uint256 size = CIRCUIT_SIZE;
        if (_unshieldingCommitments.length != size) revert WrongCircuitSize(size, _unshieldingCommitments.length);
        if (_nullifiers.length != size) revert WrongCircuitSize(size, _nullifiers.length);
        if (_recipientCommitmentsHashes.length != size) {
            revert WrongCircuitSize(size, _recipientCommitmentsHashes.length);
        }

        // head + unshielding (3 fields each) + nullifiers + recipient commitments
        publicInputs = new bytes32[](PUBLIC_INPUTS_HEAD + size * 5);

        publicInputs[0] = bytes32(_roots.localRoot);
        publicInputs[1] = bytes32(_roots.localEdgeIndex);
        publicInputs[2] = bytes32(_roots.gigaRoot);
        publicInputs[3] = bytes32(_roots.gigaEdgeIndex);
        publicInputs[4] = bytes32(gigaFirstValidIndex);
        publicInputs[5] = bytes32(gigaLastValidIndex);
        publicInputs[6] = bytes32(uint256(gigaIndex)); // current_giga_index
        publicInputs[7] = bytes32(_timeStamps.proofExpireTimeStamp);
        publicInputs[8] = bytes32(_timeStamps.historicTimeStamp);
        publicInputs[9] = bytes32(_publicHash);

        uint256 unshieldingOffset = PUBLIC_INPUTS_HEAD;
        uint256 nullifiersOffset = unshieldingOffset + size * 3;
        uint256 recipientsOffset = nullifiersOffset + size;
        for (uint256 i = 0; i < size; i++) {
            publicInputs[unshieldingOffset + i * 3] = bytes32(_unshieldingCommitments[i].recipient);
            publicInputs[unshieldingOffset + i * 3 + 1] = bytes32(_unshieldingCommitments[i].amount);
            publicInputs[unshieldingOffset + i * 3 + 2] = bytes32(_unshieldingCommitments[i].assetId);
            publicInputs[nullifiersOffset + i] = bytes32(_nullifiers[i]);
            publicInputs[recipientsOffset + i] = bytes32(_recipientCommitmentsHashes[i]);
        }
    }

    //----------------------------

    // Takes a symbol like USDC -> wtUSDC@eth for example on L1
    // Maybe wt:USDC@eth, wt:USDC:eth
    function _getTokenSymbol(string memory _baseTokenSymbol) private view returns (string memory) {
        return string.concat(symbolPreFix, _baseTokenSymbol, "@", chainSymbol);
    }

    // Takes a name like "USD Coin " -> "Wrapped Warptoad USD Coin Ethereum"  for example on L1
    function _getTokenName(string memory _baseTokenName) private view returns (string memory) {
        return string.concat("Wrapped ", namePreFix, " ", _baseTokenName, " ", chainName);
    }

    // --- ERC-20 wrapping ---------------------------------------------------------------

    /**
     * TODO make a helper to wrap and shield in 1 go
     * `_amount` is deposited here and `_to` receives wrapped token as claim on this deposit
     * @notice Creates a new wrapper token contract from a openzeppelin clone factory
     * if it does not exist yet
     * @return wrapper The wrapper token minted.
     * @return minted Amount minted, which can differ from _amount on some tokens
     * like fee on transfer tokens.
     */
    function wrapERC20(address _token, uint256 _amount, address _to)
        external
        nonReentrant
        returns (address wrapper, uint256 minted)
    {
        if (closedPools[_token]) revert PoolIsClosed(_token);

        wrapper = _getOrCreateERC20Wrapper(_token);

        // Check before balance to deal with fee on transfer tokens causing insolvency
        uint256 balanceBefore = IERC20(_token).balanceOf(address(this));
        IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
        minted = IERC20(_token).balanceOf(address(this)) - balanceBefore;

        WarptoadERC20(wrapper).mint(_to, minted);
        emit ERC20Wrapped(_token, wrapper, _to, minted);
    }

    /**
     * @notice Burns `_amount` of `_wrapper` from the caller and releases the same
     * amount of underlying collateral to `_to`.
     * @return token The underlying released.
     */
    function unwrapERC20(address _wrapper, uint256 _amount, address _to)
        external
        nonReentrant
        returns (
            address token // @TODO no definitions in returns. It's a foot gun jimjim fucks up a lott
        )
    {
        token = underlyingOf[_wrapper].token;
        if (token == address(0) || erc20WrapperOf[token] != _wrapper) revert NotAWrapper(_wrapper);

        WarptoadERC20(_wrapper).burn(msg.sender, _amount);
        IERC20(token).safeTransfer(_to, _amount);

        emit ERC20Unwrapped(token, _wrapper, _to, _amount);
    }

    /**
     * automatically deploy a wrapper contract clone if it does not exist yet
     * @param _token which underlying to wrap
     */
    function _getOrCreateERC20Wrapper(address _token) private returns (address wrapper) {
        wrapper = erc20WrapperOf[_token];
        if (wrapper != address(0)) return wrapper;

        // deploy the contract
        wrapper = address(
            new WarptoadERC20(
                _token,
                _getTokenName(TokenMetadata.nameOf(_token)),
                _getTokenSymbol(TokenMetadata.symbolOf(_token)),
                TokenMetadata.decimalsOf(_token)
            )
        );

        erc20WrapperOf[_token] = wrapper;
        underlyingOf[wrapper] = Underlying({token: _token, chainWarpDomain: gigaIndex});
        emit ERC20WrapperCreated(_token, wrapper);
    }

    // is cute but wrapper tokens get burned upon shielding and get minted on different chains
    // so not a valid detection mechanism, but it might be possible if we swap out `WarptoadERC20(wrapper).totalSupply`
    // for another counter
    // function closeUndercollateralizedPool(address _token) external returns (bool closed) {
    //     address wrapper = erc20WrapperOf[_token];
    //     if (wrapper == address(0)) revert NotAWrapper(_token);
    //
    //     if (IERC20(_token).balanceOf(address(this)) >= WarptoadERC20(wrapper).totalSupply()) {
    //         return false;
    //     }
    //
    //     poolIsClosed[_token] = true;
    //     emit PoolClosed(_token);
    //     return true;
    // }

    // --- ERC-1155  wrapping -------------------------------------------------------------

    /**
     * TODO 721 just support wrapping by default.
     * `_amount` of the `_id` is deposited here and _to receives wrapped token as claim on this deposit
     * @notice Creates a new wrapper token contract from a openzeppelin clone factory
     * if it does not exist yet
     * @return wrapper The wrapper collection minted.
     */
    function wrapERC1155(address _collection, uint256 _id, uint256 _amount, address _to)
        external
        nonReentrant
        returns (address wrapper)
    {
        if (closedPools[_collection]) revert PoolIsClosed(_collection);

        wrapper = _getOrCreateERC1155Wrapper(_collection);

        IERC1155(_collection).safeTransferFrom(msg.sender, address(this), _id, _amount, "");
        WarptoadERC1155(wrapper).mint(_to, _id, _amount);

        emit ERC1155Wrapped(_collection, wrapper, _to, _id, _amount);
    }

    //wrapERC721

    /**
     * @notice Burns `_amount` of `_wrapper`'s token `_id` from the caller and
     * releases the underlying collateral to `_to`.
     * @return collection The underlying collection released.
     */
    function unwrapERC1155(address _wrapper, uint256 _id, uint256 _amount, address _to)
        external
        nonReentrant
        returns (address collection)
    {
        collection = underlyingOf[_wrapper].token;
        if (collection == address(0) || erc1155WrapperOf[collection] != _wrapper) revert NotAWrapper(_wrapper);

        WarptoadERC1155(_wrapper).burn(msg.sender, _id, _amount);
        IERC1155(collection).safeTransferFrom(address(this), _to, _id, _amount, "");

        emit ERC1155Unwrapped(collection, _wrapper, _to, _id, _amount);
    }

    /**
     * @dev ERC-1155 has no standard name/symbol, so both are read best-effort from
     * the collection and fall back to its address.
     */
    function _getOrCreateERC1155Wrapper(address _collection) private returns (address wrapper) {
        wrapper = erc1155WrapperOf[_collection];
        if (wrapper != address(0)) return wrapper;

        wrapper = address(
            new WarptoadERC1155(
                _collection,
                _getTokenName(TokenMetadata.nameOf(_collection)),
                _getTokenSymbol(TokenMetadata.symbolOf(_collection))
            )
        );

        erc1155WrapperOf[_collection] = wrapper;
        underlyingOf[wrapper] = Underlying({token: _collection, chainWarpDomain: gigaIndex});
        emit ERC1155WrapperCreated(_collection, wrapper);
    }
}
