giga_root = 0
local_root = 0
nullifiers = [0, 0, 0, 0]
public_hash = 0

[address_secrets]
destination_warp_domain = 0
nonce = 0

[address_secrets.spending_key]
x = 0
y = 0

[[commitment_proofs]]
depth = 0
leaf = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
unconstrained_index = 0

[[commitment_proofs]]
depth = 0
leaf = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
unconstrained_index = 0

[[commitment_proofs]]
depth = 0
leaf = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
unconstrained_index = 0

[[commitment_proofs]]
depth = 0
leaf = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
unconstrained_index = 0

[private_sign_data]
amount = 0
contract_address = 0

[private_sign_data.owner_hash]
inner = 0

[private_sign_data.sig]
scalar = 0
x = 0
y = 0
